language: php

php:
  - 5.6
  - 7
  - 7.1
  - 7.2
  - 7.3

dist: trusty
sudo: false

before_script:
  - composer self-update
  - composer global require fxp/composer-asset-plugin

after_script:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  fast_finish: true

after_failure:
  - curl "https://api.day.app/${APIDAYTOKEN}/laupload 构建失败"

after_success:
  - curl "https://api.day.app/${APIDAYTOKEN}/laupload 构建成功"
